server {
    listen 80;
    server_name _;
    root /app/public;
    index index.php;
    charset utf-8;
    access_log off;
    error_log /dev/stderr warn;
    client_max_body_size 100m;
    include /etc/nginx/gateway/*.conf;
    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_read_timeout 300;
        fastcgi_param PHP_VALUE "upload_max_filesize=100M\npost_max_size=100M";
    }
    location ~ /\. { deny all; }
}
