<?php

namespace Pterodactyl\Services\Nodes;

/** Fixed upstream gateway for the panel's nginx server; no user-selected targets. */
class NginxGateway
{
    public static function browserAddress(int $id, string $panelUrl): string
    {
        if ($id < 1) {
            throw new \InvalidArgumentException('Node IDs must be positive integers.');
        }

        return PublicEndpoint::resolve(0, '', [0 => $panelUrl], false) . '/_wings/' . $id;
    }

    /** @param array<int, string> $nodes node ID => INTERNAL Wings origin */
    public static function render(array $nodes): string
    {
        $result = "# Generated by p:remote-access:nginx. Include INSIDE the panel server {}.\n";
        $result .= "# Regenerate after adding/removing nodes or changing their internal addresses.\n";
        $result .= "location ^~ /_wings/ { return 404; }\n\n";
        ksort($nodes);
        foreach ($nodes as $id => $url) {
            if (!is_int($id) || $id < 1) {
                throw new \InvalidArgumentException('Node IDs must be positive integers.');
            }
            $url = PublicEndpoint::resolve($id, '', [$id => $url], false);
            // Only literal DNS names/IPs: nginx variables or config syntax must never be emitted.
            $host = parse_url($url, PHP_URL_HOST);
            if (!preg_match('/\A[a-zA-Z0-9.\-:\[\]]+\z/', $host)) {
                throw new \InvalidArgumentException("Unsafe upstream hostname for node {$id}.");
            }
            $tls = '';
            if (str_starts_with($url, 'https://')) {
                $tls = "    proxy_ssl_server_name on;\n    proxy_ssl_verify on;\n    proxy_ssl_verify_depth 3;\n    proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;\n";
            }
            $block = <<<'NGINX'
location ^~ /_wings/__ID__/ {
    # Only the four JWT-protected browser endpoints, never the daemon admin API.
    if ($uri !~ "^/_wings/__ID__/(api/servers/[0-9a-fA-F-]{36}/ws|download/(file|backup)|upload/file)$") { return 404; }
    if ($request_method !~ "^(GET|HEAD|POST|OPTIONS)$") { return 405; }
    set $wings_upgrade_connection "";
    if ($http_upgrade = websocket) { set $wings_upgrade_connection upgrade; }
    rewrite ^/_wings/__ID__/(.*)$ /$1 break;
    proxy_pass __UPSTREAM__;
    proxy_http_version 1.1;
    proxy_set_header Host $proxy_host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $wings_upgrade_connection;
    proxy_set_header Origin $http_origin;
    proxy_set_header Cookie "";
    proxy_set_header Authorization "";
    proxy_set_header X-CSRF-TOKEN "";
    proxy_set_header X-XSRF-TOKEN "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_hide_header Set-Cookie;
    proxy_hide_header Content-Security-Policy;
    proxy_ignore_headers X-Accel-Redirect;
    # User files now share the panel origin: never permit active downloaded content.
    add_header Content-Security-Policy "sandbox; default-src 'none'" always;
    add_header X-Content-Type-Options nosniff always;
    proxy_cache off;
    proxy_buffering off;
    proxy_request_buffering off;
    proxy_connect_timeout 10s;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    # Wings still enforces its configured upload limit; avoid nginx's default 1MB cap.
    client_max_body_size 0;
    # Signed URLs include JWTs; do not log them in the gateway access log.
    access_log off;
__TLS__}

NGINX;
            $result .= str_replace(['__ID__', '__UPSTREAM__', '__TLS__'], [(string) $id, $url, $tls], $block) . "\n";
        }

        return $result;
    }
}
